function [ ] = block_Schwarz_plotres( SOLVERparams )
%BLOCK_SCHWARZ_PLOTRES plots convergence history of residuals generated by 
% the multiplicative Schwarz method and the GMRES method.
%
%   function call:
%
%          [  ] = block_Schwarz_plotres( SOLVERparams )
%
%   input:
%
%   SOLVERparams: data structure with solver parameters.
%           res_s: the residuals generated by the mult. Schwarz method.
%                  they are obtained from the function
%                  Multiplicative_Schwarz.m
%           res_g: residuals of the GMRES method. generated by the file
%                  Shishkin_script.m
%
%   output:
%
%  figure showing the residual history of the GMRES and Schwarz methods.
%
% Written by Carlos Echeverria on September 23, 2016.
% Last Edited by C. E. on January 28, 2019.

  res_s = SOLVERparams.res_s;
  res_g = SOLVERparams.res_g;


figure(501); clf;
semilogy(0:length(res_s)-1,res_s/res_s(1),'r-'); hold on;
semilogy(0:length(res_g)-1,res_g/res_g(1));
axis([0 (length(res_g)) 1e-12 1e0]);
grid on
figure(501), set(gca,'XTick',[1,2,3,4,5,10,15,20,25,30,35,40,50,60,70,80,90,100,130,160,190,220,250,300,350,400,450,500,600,700,800,900,1000])
%hold off;
set(gca,'FontSize',18)
xlabel('Iterations','FontSize',18);
ylabel('Relative Residual','FontSize',18);
legend('Multiplicative Schwarz','GMRES','Location','South');
title('GMRES vs. Multiplicative Schwarz')


end
